Added test cases for Month
AY2324S1-CS2103-F13-2/tp pull request #84
Opened 2023-10-20 04:46 UTC by remuslum

Testing of Month

The current codebase does not have the test cases to ensure the functionality of Month.

Hence, I have made the necessary class MonthTest and the test cases.

2023-10-20 08:08 UTC, nixonwidjaja requested changes
Please add test cases for MatchingMonthPredicate and Parser Util
More details: https://github.com/AY2324S1-CS2103-F13-2/tp/pull/78

2023-10-26 05:06 UTC, sheryew approved these changes
LGTM!

2023-10-26 05:07 UTC, sheryew approved these changes
lgtm!

2023-10-26 10:49 UTC, nixonwidjaja approved these changes

2023-10-26 10:49 UTC, merged